Update drone.yml workspace path and test step
drone-plugins/drone-coverage pull request #18
Opened 2016-10-24 01:30 UTC by fbcbarbosa

Hardcode path, so `drone exec` will work in any environment.

Make go test iterate through every package, so it runs coverage in all of them, instead of just testing the root folder (which incidentally contains no test files).

2016-10-24 01:34 UTC, fbcbarbosa commented
Before:

![image](https://cloud.githubusercontent.com/assets/7269710/19631281/1d62abf2-9979-11e6-9676-7be6fcfdfc26.png)

Now:

![image](https://cloud.githubusercontent.com/assets/7269710/19631287/2bc755ee-9979-11e6-8610-1a00399b841e.png)

2016-10-30 13:31 UTC, fbcbarbosa commented
Also, it seems drone did not run after the last push. Maybe it's been configured to run on PR, but not on push (which I guess would be the preferred behavior)?

2016-10-30 13:47 UTC, tboerger requested changes

2016-10-30 13:47 UTC, tboerger commented on .drone.yml
> +          go test "$line" -cover -coverprofile=coverage-"$name".out
Do it like https://github.com/drone-plugins/drone-coverage/blob/release/0.4/Makefile#L25

2016-10-30 13:47 UTC, tboerger commented on .gitignore
> +*.swp
This should not be part of the gitignore, that should be handled on your own global gitignore.

2016-10-30 13:47 UTC, tboerger commented on .gitignore
> +coverage*.out
Just drop that change, the old ignore will be matched if you do it like the old makefile.

2016-10-30 13:47 UTC, tboerger commented on .gitignore
> +coverage.xml
Where does the xml format come from?

2016-10-30 14:13 UTC, fbcbarbosa commented on .drone.yml
> +          go test "$line" -cover -coverprofile=coverage-"$name".out
Ok, will do!

2016-10-30 14:13 UTC, fbcbarbosa commented on .gitignore
> +*.swp
Ok

2016-10-30 14:13 UTC, fbcbarbosa commented on .gitignore
> +coverage*.out
Alright

2016-10-30 14:15 UTC, fbcbarbosa commented on .gitignore
> +coverage.xml
Yeah, I can remove this. Cobertura uses xml files so I added a few on my local environment for testing, but it doesn't need to go on .gitignore, my bad.

2016-10-30 23:06 UTC, fbcbarbosa commented
@tboerger updated PR, please check if it's ok now :+1:

2016-10-31 19:45 UTC, tboerger approved these changes

2016-10-31 19:46 UTC, tboerger commented
LGTM

2016-11-08 01:39 UTC, donny-dont approved these changes

2016-11-08 01:39 UTC, donny-dont commented on .drone.yml
>        - go test -coverprofile=coverage.out
This line can be gotten rid of correct?

2016-11-08 01:39 UTC, donny-dont commented
LGTM

2016-11-08 01:39 UTC, merged